//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Semantix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cliente_Endereco = new HashSet<Cliente_Endereco>();
            this.Cliente_Telefone = new HashSet<Cliente_Telefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Cliente_Endereco> Cliente_Endereco { get; set; }
        public virtual ICollection<Cliente_Telefone> Cliente_Telefone { get; set; }
    }
}
